language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - vendor

# Don't run the default Travis PHP install step
install: true

before_install:
  - composer install

script:
  - ./config/part/phplint.sh
  - ./config/part/phpunit.sh