language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - vendor

# Don't run the default Travis PHP install step
install: true

before_install:
  - composer install

script:
  - ./bin/phpcs -p
  - ./bin/phpmd --exclude '*Test.php,*TestCase.php' ./Scraper/ text codesize
  # Phan has minimum dependency of PHP 7.1
  #- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then ./travis/phan.sh; fi
  - ./travis/phpsa.sh
  - ./bin/concise