language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - vendor

# Don't run the default Travis PHP install step
install: true

before_install:
  - composer install

script:
  - ./bin/phpcs -p
  - ./config/part/phpunit.sh